### ISSUE TITLE
CannotRetrieveUpdates alert

### ISSUE THREAD

**Issue by yselkowitz** [openshift/ocp-on-arm#13]
Nightly builds (for all architectures) are not upgradable.  Therefore, after a while, you will see a `CannotRetrieveUpdates` alert.  This is normal under the circumstances, and can be silenced or avoided by setting Channel in the Administration->Cluster Settings page to the empty string, or with the following command:
```
oc patch clusterversion.config.openshift.io/version -p='{"spec":{"channel":""}}' --type=merge
```

**Comment by Prashanth684** [comment]
with the latest build the update channel now points to stable-4.8 and gives this message:

```
Upstream is unset, so the cluster will use an appropriate default.
Channel: stable-4.8
warning: Cannot display available updates:
  Reason: VersionNotFound
  Message: Unable to retrieve available updates: currently reconciling cluster version 4.9.0-0.nightly-arm64-2021-08-16-154214 not found in the "stable-4.8" channel
```

which is normal until 4.9 GA's ?

**Comment by yselkowitz** [comment]
That is normal for any nightly.

**Comment by yselkowitz** [comment]
The Dev Preview is no longer a nightly release and so update channels should be found.
