### ISSUE TITLE
Single Node OpenShift on ARM

### ISSUE THREAD

**Issue by kaovilai** [openshift/ocp-on-arm#20]
Would love to have this run on raspberry pi 4

**Comment by yselkowitz** [comment]
Work on Single Node OpenShift is ongoing; currently it can be installed on AWS by adjusting the `install-config.yaml` to have only one controlPlane node (which then needs to be specified to be at least `m6g.2xlarge` or larger) and zero worker nodes.

As for the RasPi, only RHEL-compatible machines will be considered for OpenShift enablement, and RHEL for ARM requires ServerReady SR compliance along with device driver support in the upstream kernel.  (For more information, see https://access.redhat.com/solutions/6673691.)  The RasPi fulfills neither condition.  Furthermore, while 8 GB memory is usually sufficient for a minimal worker node, it is generally insufficient for a control plane node, particularly in a 3NO or SNO configuration.

However, you may want to try MicroShift as an alternative; https://next.redhat.com/2022/01/19/introducing-microshift/ mentions the RasPi4 as a possible target.  Please note that MicroShift is not officially supported, so please do not raise issues here about it.

I hope you find this information helpful.

/close

**Comment by kaovilai** [comment]
Well isn't it an ongoing issue? Or are you tracking elsewhere as well?

**Comment by yselkowitz** [comment]
The 4.9 developer preview is only targeting AWS, and you can try SNO on AWS right now as described above.  Other platforms are out of scope for this issue tracker.

**Comment by LorbusChris** [comment]
Side note: Using this firmware for the RPi, one can actually make it sufficiently SBBR-compliant for deployment of Fedora CoreOS (and probably RHEL CoreOS too): https://github.com/pftf/RPi4
Obviously that requires the creation of a custom boot image.
And there's still the issue of insufficient memory for OpenShift masters.
